2018-12-18 22:59:52,316 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-18 23:00:11,743 ERROR: Exception on /user/Alex [GET] [in c:\homework\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\homework\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\HomeWork\app\routes.py", line 75, in user
    return render_template('user.html', title='Учетная запись', user=user, posts=posts)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\homework\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\HomeWork\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\HomeWork\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\HomeWork\app\templates\user.html", line 12, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Редактировать учетную запись</a></p>
  File "c:\homework\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\homework\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
2018-12-18 23:01:54,186 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-18 23:03:01,317 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-19 00:41:06,616 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:07:06,879 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:07:37,898 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:07:56,475 ERROR: Exception on /user/Alex [GET] [in c:\homework\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\homework\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\homework\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\HomeWork\app\routes.py", line 75, in user
    return render_template('user.html', title='Учетная запись', user=user, posts=posts)
  File "c:\homework\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\homework\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\homework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\HomeWork\app\templates\user.html", line 15, in template
    <p><a href="{{ url_for('follow'), username=user.username }}">Подписаться</a></p>
  File "c:\homework\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\homework\venv\lib\site-packages\jinja2\parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "c:\homework\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2018-12-20 00:12:55,068 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:16:51,156 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:22:34,618 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:24:19,225 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:26:19,410 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-20 00:27:26,737 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-24 23:42:31,887 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
2018-12-24 23:43:04,068 INFO: Microblog startup [in C:\HomeWork\app\__init__.py:28]
